---
- id: debug
  name: Debug pre-commit hook calls
  entry: hooks/debug.sh
  language: script

- id: npm-groovy-lint
  name: Lint Groovy code
  entry: /usr/bin/npm-groovy-lint --noserver
  language: script
  types: [groovy]

- id: doctoc
  name: Generates Table Of Contents in Markdown files
  entry: /usr/bin/doctoc
  language: script
  types: [markdown]

- id: markdownlint
  name: Lint with markdownlint
  entry: /usr/bin/markdownlint
  language: script
  types: [markdown]

- id: dockerfile_lint
  name: Lint Dockefile with dockerfile_lint
  entry: /usr/bin/dockerfile_lint --dockerfile
  language: script
  types: [dockerfile]

- id: cf-doc
  name: Generate docs from CloudFormation templates
  entry: hooks/cf-doc.sh
  language: script
  types: [text, yaml]

- id: terraform_validate
  name: Lint Terraform templates
  description: Validates all Terraform configuration files.
  entry: hooks/terraform_validate.sh
  language: script
  files: \.tf(vars)?$
  exclude: (^|/)\.terraform\/
  types: [terraform]
  require_serial: true

- id: terraform_format
  name: Format Terraform templates
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: hooks/terraform_format.sh
  language: script
  files: \.tf(vars)?$
  exclude: (^|/)\.terraform\/
  types: [terraform]
  require_serial: true

- id: ansible_playbook
  name: Ansible playbook syntax check
  entry: hooks/ansible-playbook.sh
  language: script
  types: [yaml]

- id: ansible_lint
  name: Lint Ansible
  entry: /usr/local/bin/ansible-lint
  language: script
  types: [yaml]

- id: pycodestyle
  name: Style guide checker of Python code
  entry: /usr/local/bin/pycodestyle
  language: script
  types: [python]

- id: cfn-lint
  name: AWS CloudFormation Linter
  entry: /usr/local/bin/cfn-lint
  language: script
  types: [yaml, json]

- id: pylint
  name: pylint
  entry: /usr/local/bin/pylint
  language: script
  types: [python]
  require_serial: true

- id: yamllint
  name: yamllint
  entry: /usr/local/bin/yamllint
  language: script
  types: [yaml]
