---
- id: debug
  name: Debug pre-commit hook calls
  entry: hooks/debug.sh
  language: script

- id: cf-doc
  name: Generate docs from CloudFormation templates
  entry: hooks/cf-doc.sh
  language: script
  types: [text, yaml]

- id: terraform_validate
  name: Lint Terraform templates
  description: Validates all Terraform configuration files.
  entry: hooks/terraform_validate.sh
  language: script
  files: \.tf(vars)?$
  exclude: (^|/)\.terraform\/
  types: [terraform]
  require_serial: true

- id: terraform_format
  name: Format Terraform templates
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: hooks/terraform_format.sh
  language: script
  files: \.tf(vars)?$
  exclude: (^|/)\.terraform\/
  types: [terraform]
  require_serial: true

- id: ansible_playbook
  name: Ansible playbook syntax check
  entry: hooks/ansible-playbook.sh
  language: script
  types: [yaml]
