---
- id: npm-groovy-lint
  name: Lint Groovy code
  entry: hooks/npm-groovy-lint
  language: script
  types: [text, groovy]

- id: terraform_validate
  name: Lint Terraform templates
  entry: hooks/tf_validate.sh
  language: script
  files: \.tf$
  exclude: \.terraform\/
