#!/bin/sh
set -eu

################################################################################
# Lint Groovy code.
################################################################################

readonly DEBUG=${DEBUG:-unset}
if [ "${DEBUG}" != unset ]; then
  set -x
fi

npm-groovy-lint --noserver "$@"
